### PR TITLE
Unified build script

### PR DESCRIPTION
**Pull request by SinTh0r4s**
Should the lang repository be kept or resolved into the file sctructure as it is now?

There are also issues with textures. Some especially machines, cannot be found.

Does anybody know what the content of folder `forestry_techne` is for?

Should we extract [CraftGuide](https://github.com/Uristqwerty/CraftGuide/tree/1.7.10) and add the mod/lib to the pack? Railcraft adds it the same way. I am surprised there were no issues with it.

### CODE REVIEW

**Comment by draknyte1** [comment]
> Does anybody know what the content of folder forestry_techne is for?

probably techne models?

**Comment by SinTh0r4s** [comment]
> > Does anybody know what the content of folder forestry_techne is for?
> 
> probably techne models?

But what is that?

**Comment by mitchej123** [comment]
> > > Does anybody know what the content of folder forestry_techne is for?
> > 
> > 
> > probably techne models?
> 
> But what is that?

https://fileinfo.com/extension/tcn

**Comment by draknyte1** [comment]
Techne

iyrB2UvJVW1Nq1_4214006

**Comment by SinTh0r4s** [comment]
\
It would be amazing if anybody could figure this out!

**Pull request merged**
