### PR TITLE
Ic2 crop module

### PR DESCRIPTION
**Pull request by bartimaeusnek**

### CODE REVIEW

**Comment by repo-alt** [comment]
It would be much easier to review if you would not mix string constants refactoring in one commit with the other changes. Anyway, I noticed nothing wrong.

**Review by repo-alt — APPROVED** [review]

**Comment by Prometheus0000** [comment]
OK, so you added an IC2 crops mode to the farm. But what does that actually mean? How is it different from orchard mode?

**Comment by Glease** [comment]
There is currently no difference, except it will not check for anything else than IC2 cropsticks, making it a little bit faster perhaps. bart also says he want to do some more optimization in the comment but that's all.

**Comment by Prometheus0000** [comment]
Yeah, that's not what I read in general.
image
image
image

**Comment by repo-alt** [comment]
Being in separate module it is easier to optimize anyway. Also the PR is unfinished

**Comment by bartimaeusnek** [comment]
@repo-alt the constants refactoring was done so i could easier develop, but ye sure, shouldve done that in 2 commits.

**Comment by Dream-Master** [comment]
@bartimaeusnek @repo-alt any news?

**Pull request merged**
