### PR TITLE
Remove NEI-Hidden Bees feature

### PR DESCRIPTION
**Pull request by Runakai1**
Removed the invisibility of certain bees to be shown in NEI, since it's showing it in different tabs anyway.

### CODE REVIEW

**Review by miozune — COMMENTED** [review]
Can we make `setIsSecret` do nothing so that addons will be affected as well?

**Comment by Runakai1** [comment]
> Can we make `setIsSecret` do nothing so that addons will be affected as well?

Sorry, got so many Emails I just noticed this. I made it return false if that's okay so it should be always visible

**Comment by boubou19** [comment]
you may want to add a comment explaining why it was done

**Comment by DianeXD** [comment]
iirc beebetteratbees.cfg and NEIAddons.cfg have configuration options to show secret mutations

**Comment by Runakai1** [comment]
> iirc beebetteratbees.cfg and NEIAddons.cfg have configuration options to show secret mutations

You are right. This PR isnt needed then, I guess

**Pull request closed without merging**
