### PR TITLE
Make CoFHCore required

### PR DESCRIPTION
**Pull request by kuba6000**
Required here: https://github.com/GTNewHorizons/ForestryMC/blob/master/src/main/java/forestry/apiculture/multiblock/TileAlvearyClimatiser.java

### CODE REVIEW

**Comment by glowredman** [comment]
Couldn't you just do an `@Optional.Interface` annotation instead?

**Comment by kuba6000** [comment]
It is used in other classes too to handle power (drain/output). 
image
I used Climatiser as an example because it is in crashlog

**Comment by Connor-Colenso** [comment]
This fixes multiple annoying vague crashes that I have encountered before because forestry is a dep of bartworks which is a dep of multiple GT addons.

**Review by Connor-Colenso — APPROVED** [review]

**Comment by glowredman** [comment]
@Connor-Colenso why did you merge this? The discussion was still open!

**Comment by Dream-Master** [comment]
Colen be „mergemasterXXL even faster“ 😎

**Comment by Connor-Colenso** [comment]
> @Connor-Colenso why did you merge this? The discussion was still open!

I mean there is a "nicer" way to handle this but this resolves the issue for now. I asked Kuba to open this PR because of crashes being caused in GT5 dev environments from the new GT apiary. If you have a more elegant solution then open a new PR with it and I'll happy merge it 😛

**Comment by tyrael93** [comment]
(commented on the commit instead of the pull, my bad.)

I'm sorry, is this a hard dependency on CoFHCore, as in it will be impossible to use this fork without it?
What's the purpose of this change? I've noticed a lot of other GTNH forks have switched to an optional dependency which can be toggled off in the configs instead. Wouldn't that be more suitable for general use? I personally use this mod as an unofficial fork for the QoL changes compared  to the now defunct main version of forestry for 1.7, I thought the days of adding hard dependencies to GTNH forks were over years ago.

**Comment by Connor-Colenso** [comment]
Yea you are right and we've discussed it on discord extensively. The hard dep was a bad decision on my part given I asked kuba to do this. 

PRs fixing this will be accepted asap but I'm a bit busy atm.

**Pull request merged**
